name: "新しい記事の追加/編集"
description: "新しい記事の追加または既存の記事の編集"
title: "[記事]: "
labels: ["article"]

body:
  - type: "dropdown"
    id: pr_type
    attributes:
      label: "PRの種類"
      description: "新しい記事の追加または既存の記事の編集を選択してください"
      multiple: false
      options:
        - "新しい記事の追加"
        - "既存の記事の編集"
      default: 0
    validations:
      required: true
